name = "message-worker"
main = "worker-message.js"
type = "javascript"

account_id = "4796a78c1804791b739f97bb336bab79"
zone_id = "df09b3a563bde936907cc7c4a710f942"

compatibility_date = "2025-07-08"

workers_dev = true

routes = ["message.0515364.xyz/*"]

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "message"
preview_bucket_name = "message"
