name = "access"
main = "worker.js"
type = "javascript"
account_id = "4796a78c1804791b739f97bb336bab79"
zone_id = "df09b3a563bde936907cc7c4a710f942"
compatibility_date = "2025-07-03"

workers_dev = true
routes = ["*.0515364.xyz/*"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
