name = "inject-menu-worker"
type = "javascript"
account_id = "4796a78c1804791b739f97bb336bab79"
compatibility_date = "2025-09-08"
workers_dev = false
route = "0515364.xyz/*"
zone_id = "df09b3a563bde936907cc7c4a710f942"

[build]
upload_format = "service-worker"