name: Deploy Cloudflare Worker

on:
  push:
    branches: [main]
    paths:
      - 'Cloudflare/worker.js'
      - 'Cloudflare/wrangler.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler v2
        run: npm install -g wrangler@2

      - name: Publish Worker
        run: wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}