name: Deploy pan-worker (网盘)

on:
  push:
    branches: [main]
    paths:
      - 'Cloudflare/pan/*.js'  # 只监控.js文件的变化
      - 'Cloudflare/pan/wrangler-pan.toml'  # 配置文件变化也要触发
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler v2
        run: npm install -g wrangler@2

      - name: Publish pan-worker to Cloudflare
        working-directory: Cloudflare/pan/
        run: |
          wrangler publish --config wrangler-pan.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}