name: Cloudflare Pan Worker CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'Cloudflare/worker-pan.js'
      - 'Cloudflare/wrangler-pan.toml'
      - 'Cloudflare/worker.js'
      - 'Cloudflare/wrangler.toml'
      - 'Cloudflare/access.json'
      - 'Cloudflare/wrangler-access.toml'
  workflow_dispatch:

jobs:
  deploy-pan-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Wrangler v2
        run: npm install -g wrangler@2
      - name: Publish pan-worker to Cloudflare
        working-directory: Cloudflare
        run: wrangler publish --config wrangler-pan.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Wrangler v2
        run: npm install -g wrangler@2
      - name: Publish Worker
        working-directory: Cloudflare
        run: wrangler publish --config wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  upload-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Wrangler v2
        run: npm install -g wrangler@2

      - name: Copy wrangler-access.toml to wrangler.toml
        run: cp Cloudflare/wrangler-access.toml Cloudflare/wrangler.toml

      - name: Upload access.json to R2
        working-directory: Cloudflare
        env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "🧩 Uploading access.json..."
          wrangler r2 object put access.json --file=access.json --bucket=mypan