name: Deploy Inject Menu Worker (菜单页脚)

on:
  push:
    branches: [main]
    paths:
      - 'Cloudflare/menu/worker-menu.js'
      - 'Cloudflare/menu/wrangler-menu.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler v2
        run: npm install -g wrangler@2

      - name: Publish Worker
        working-directory: Cloudflare/menu
        run: wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}